import os
import shutil
import subprocess
import re
import json
import glob

# ==========================================
# CONFIGURATION & GPU FORCING
# ==========================================
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
INPUT_DIR = os.path.join(BASE_DIR, "input")
OUTPUT_DIR = os.path.join(BASE_DIR, "output")
TEMP_DIR = os.path.join(BASE_DIR, "temp_staging")

# Optional runtime settings. Set these in your shell if your environment needs them.
# Examples: TORCH_DEVICE=cuda, INFERENCE_RAM=20, OMP_NUM_THREADS=1

def sanitize_filename(name):
    name = re.sub(r'[^\w\.-]', '_', name) 
    name = re.sub(r'_{2,}', '_', name)    
    return name

def inject_metadata(md_content, meta_path):
    if not os.path.exists(meta_path):
        return md_content
    try:
        with open(meta_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        title = data.get('title', 'Unknown Title')
        authors = data.get('authors', [])
        author_str = ", ".join(authors) if isinstance(authors, list) else "Unknown Author"
        
        frontmatter = f"---\nTitle: {title}\nAuthor: {author_str}\n---\n\n"
        print(f"   [+] Injected Metadata: {title} by {author_str}")
        return frontmatter + md_content
    except Exception as e:
        print(f"   [!] Metadata injection failed: {e}")
        return md_content

def clean_text(content):
    """
    Refined for Maximum Quality Heuristic Extraction.
    """
    # 1. Tag images logically for Context Anchors
    content = re.sub(r'!\[(.*?)\]\(.*?\)', r'[CONTEXT_ANCHOR_VISUAL: \1]', content)

    # 2. Remove HTML Spans but keep the text inside them
    content = re.sub(r'<span[^>]*>(.*?)</span>', r'\1', content)

    # 3. Format Citations instead of deleting them (Preserves logic mapping)
    content = re.sub(r'\[(\d+(?:,\s*\d+)*)\]', r' [CITATION: \1] ', content)

    # 4. Preserve copyright, attribution, and publication information.
    # These notices are part of the source record and must not be removed.

    # 5. Remove malformed table-of-contents artifacts only.
    content = re.sub(r'\|[ \d<br>\|]+(?:Section|Chapter|Index).*?\|', '', content, flags=re.IGNORECASE | re.DOTALL)

    # 5b. REMOVE EPUB HYPERLINK TOCs (The New Fix)
    # Detects bulleted lists containing local file paths or HTML anchor links generated by EPUBs
    content = re.sub(r'(?m)^[-*]\s+\[.*?\]\([^\)]*(?:file:///|\.html#|#filepos)[^\)]*\).*?\n', '', content)

    # 6. Fix broken paragraph line breaks (Common OCR/PDF artifact)
    content = re.sub(r'(?<!\n)\n(?!\n)(?=[a-z])', ' ', content)
    
    # 7. Remove excess whitespace/blank lines (more than 2)
    content = re.sub(r'\n{3,}', '\n\n', content)

    return content

def process_books():
    if not os.path.exists(TEMP_DIR):
        os.makedirs(TEMP_DIR)
    
    extensions = ['*.epub', '*.pdf']
    files_to_process = []
    
    for ext in extensions:
        files_to_process.extend(glob.glob(os.path.join(INPUT_DIR, ext)))

    print(f"Found {len(files_to_process)} books to process.")

    for file_path in files_to_process:
        original_name = os.path.basename(file_path)
        safe_name = sanitize_filename(original_name)
        staged_path = os.path.join(TEMP_DIR, safe_name)

        print(f"\n==========================================")
        print(f"PROCESSING: {original_name}")
        print(f"==========================================")

        shutil.copy2(file_path, staged_path)

        # Using the standard Marker CLI without a shell avoids quoting issues.
        cmd = ["marker_single", staged_path, "--output_dir", OUTPUT_DIR]
        try:
            subprocess.run(cmd, check=True)
        except subprocess.CalledProcessError:
            print(f"   [!] Conversion failed for {original_name}")
            continue

        book_folder_name = os.path.splitext(safe_name)[0]
        book_output_dir = os.path.join(OUTPUT_DIR, book_folder_name)
        
        md_file = os.path.join(book_output_dir, f"{book_folder_name}.md")
        meta_file = os.path.join(book_output_dir, "meta.json")

        if os.path.exists(md_file):
            print("   [+] File converted. Starting cleanup...")
            
            with open(md_file, 'r', encoding='utf-8') as f:
                raw_text = f.read()

            text_with_meta = inject_metadata(raw_text, meta_file)
            final_text = clean_text(text_with_meta)

            with open(md_file, 'w', encoding='utf-8') as f:
                f.write(final_text)
            
            print(f"   [SUCCESS] Cleaned file saved: {md_file}")
        else:
            print("   [!] Markdown file not found. Marker might have failed.")

    try:
        shutil.rmtree(TEMP_DIR)
    except:
        pass
    print("\n\nAll tasks complete.")

if __name__ == "__main__":
    process_books()
